
package UserInterface;

import ArayuzIslemleri.GirisEkranIslemleri;
import ArayuzIslemleri.RenkVeIconlar;
import MailConfig.MailIslemleri;
import SQLIslemleri.SQLKullaniciIslemleri;
import Varlık.Kullanici;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sayar
 */
public class GirisEkrani extends javax.swing.JFrame {
    
    // Değişkenler - DBIslemleri
    
    static String DB_kullanıcı = "kütüphaneSistemi";
    
    // Classlar
    
    RenkVeIconlar renkVeIconlar = new RenkVeIconlar();
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    MailIslemleri mail = new MailIslemleri();
    SQLKullaniciIslemleri sQLKullaniciIslemleri = new SQLKullaniciIslemleri(mail,DB_kullanıcı);
    GirisEkranIslemleri girisEkran;
    
    
    
    // Değişkenler
    
    public Integer posX;
    public Integer posY;
    private boolean sifreKurtarmaIslemi;
    
     private boolean sayacDurdur = false;
     private boolean sifreSonuc = false;
        
    public GirisEkrani() {
        initComponents();
        this.setLocation(dim.width/2 - this.getSize().width/2, dim.height/2 - this.getSize().height/2);
        
        jTextField_KullanıcıAdı.setText("semih1");
        jPasswordField_Sifre.setText(new String("123456"));
        
        initComponents_2(false);
    }
    
    public void initComponents_2(boolean acilis){
        jLabel_KurtarmaMesajı.setVisible(acilis);
        jLabel_Sayac.setVisible(acilis);
        jTextField_KurtarmaKodu.setVisible(acilis);
        
        jTextField_KullanıcıAdı.setVisible(!acilis);
        jPasswordField_Sifre.setVisible(!acilis);
         jLabel_SifremiUnuttum.setVisible(!acilis);
        
        if(acilis){
            jLabel_UserLogin.setIcon(renkVeIconlar.getUser2());
        }else{
             jLabel_UserLogin.setIcon(renkVeIconlar.getUser());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AnaPanel = new javax.swing.JPanel();
        jPanel_Girisİkon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_GirisParametreleri = new javax.swing.JPanel();
        jPanel_Navigasyon = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Move = new javax.swing.JLabel();
        jPanel_Kullanıcıİkon = new javax.swing.JPanel();
        jLabel_UserLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_KullanıcıAdı = new javax.swing.JTextField();
        jPasswordField_Sifre = new javax.swing.JPasswordField();
        jTextField_KurtarmaKodu = new javax.swing.JTextField();
        jLabel_SifremiUnuttum = new javax.swing.JLabel();
        jButton_GirisYap = new javax.swing.JButton();
        jLabel_KurtarmaMesajı = new javax.swing.JLabel();
        jLabel_Sayac = new javax.swing.JLabel();
        jLabel_HesabınızYoksa = new javax.swing.JLabel();
        jLabel_HesapOlustur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_AnaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_AnaPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_AnaPanelMouseDragged(evt);
            }
        });
        jPanel_AnaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_AnaPanelMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GirisEkrani.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_GirisİkonLayout = new javax.swing.GroupLayout(jPanel_Girisİkon);
        jPanel_Girisİkon.setLayout(jPanel_GirisİkonLayout);
        jPanel_GirisİkonLayout.setHorizontalGroup(
            jPanel_GirisİkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisİkonLayout.setVerticalGroup(
            jPanel_GirisİkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_GirisParametreleri.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Navigasyon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jLabel_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Move.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/move.png"))); // NOI18N
        jLabel_Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseDragged(evt);
            }
        });
        jLabel_Move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_MoveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NavigasyonLayout = new javax.swing.GroupLayout(jPanel_Navigasyon);
        jPanel_Navigasyon.setLayout(jPanel_NavigasyonLayout);
        jPanel_NavigasyonLayout.setHorizontalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NavigasyonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Move, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Minimize)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Close)
                .addGap(16, 16, 16))
        );
        jPanel_NavigasyonLayout.setVerticalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NavigasyonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_Close)
                    .addComponent(jLabel_Minimize)
                    .addComponent(jLabel_Move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jPanel_Kullanıcıİkon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_UserLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_KullanıcıİkonLayout = new javax.swing.GroupLayout(jPanel_Kullanıcıİkon);
        jPanel_Kullanıcıİkon.setLayout(jPanel_KullanıcıİkonLayout);
        jPanel_KullanıcıİkonLayout.setHorizontalGroup(
            jPanel_KullanıcıİkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_KullanıcıİkonLayout.setVerticalGroup(
            jPanel_KullanıcıİkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_KullanıcıAdı.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_KullanıcıAdı.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanıcı Adı", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jTextField_KullanıcıAdı.setPreferredSize(new java.awt.Dimension(102, 48));
        jTextField_KullanıcıAdı.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KullanıcıAdıKeyPressed(evt);
            }
        });

        jPasswordField_Sifre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField_Sifre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sifre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jPasswordField_Sifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_SifreKeyPressed(evt);
            }
        });

        jTextField_KurtarmaKodu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_KurtarmaKodu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kurtarma Kodu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jTextField_KurtarmaKodu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KurtarmaKoduKeyPressed(evt);
            }
        });

        jLabel_SifremiUnuttum.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_SifremiUnuttum.setText("Şifremi Unuttum");
        jLabel_SifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseExited(evt);
            }
        });

        jButton_GirisYap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jButton_GirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GirisYapActionPerformed(evt);
            }
        });

        jLabel_KurtarmaMesajı.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_KurtarmaMesajı.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_KurtarmaMesajı.setText("Kurtarma Kodunu Giriniz");
        jLabel_KurtarmaMesajı.setPreferredSize(new java.awt.Dimension(154, 17));

        jLabel_Sayac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Sayac.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Sayac.setText("120");

        jLabel_HesabınızYoksa.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_HesabınızYoksa.setText("Hesabınız Yoksa");

        jLabel_HesapOlustur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_HesapOlustur.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_HesapOlustur.setText("Hesap Oluştur");
        jLabel_HesapOlustur.setName(""); // NOI18N
        jLabel_HesapOlustur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_HesapOlusturMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_HesapOlusturMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_HesapOlusturMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_HesabınızYoksa)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel_HesapOlustur))
                            .addComponent(jButton_GirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_SifremiUnuttum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_KurtarmaKodu)
                            .addComponent(jPasswordField_Sifre)
                            .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel_KurtarmaMesajı, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Sayac, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KurtarmaMesajı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Sayac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_KurtarmaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_SifremiUnuttum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_GirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_HesabınızYoksa)
                    .addComponent(jLabel_HesapOlustur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_GirisParametreleriLayout = new javax.swing.GroupLayout(jPanel_GirisParametreleri);
        jPanel_GirisParametreleri.setLayout(jPanel_GirisParametreleriLayout);
        jPanel_GirisParametreleriLayout.setHorizontalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Kullanıcıİkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisParametreleriLayout.setVerticalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GirisParametreleriLayout.createSequentialGroup()
                .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Kullanıcıİkon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_AnaPanelLayout = new javax.swing.GroupLayout(jPanel_AnaPanel);
        jPanel_AnaPanel.setLayout(jPanel_AnaPanelLayout);
        jPanel_AnaPanelLayout.setHorizontalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel_Girisİkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AnaPanelLayout.setVerticalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Girisİkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered
        jLabel_Close.setIcon(renkVeIconlar.getCancel2());
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited
         jLabel_Close.setIcon(renkVeIconlar.getCancel());
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered
        jLabel_Minimize.setIcon(renkVeIconlar.getMinimize2());
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited
        jLabel_Minimize.setIcon(renkVeIconlar.getMinimize());
    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
         this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_SifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseEntered
        jLabel_SifremiUnuttum.setForeground(Color.BLACK);
        jLabel_SifremiUnuttum.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseEntered

    private void jLabel_SifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseExited
        jLabel_SifremiUnuttum.setForeground(renkVeIconlar.getKirmizi());
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseExited

    private void jLabel_SifremiUnuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseClicked
       
      String girilenkullaniciAdi = jTextField_KullanıcıAdı.getText();
        girilenkullaniciAdi = girilenkullaniciAdi.replaceAll(" ", "");
        jTextField_KullanıcıAdı.setText(girilenkullaniciAdi);
        
        Kullanici kullanici;
        
        boolean mailAdresiBulunduMu = false;
        
        if(!girilenkullaniciAdi.equals("")){  // Mail Gönderilicek
            int dialogButton = JOptionPane.showConfirmDialog(this, "Kurtarma Kodu Mailinize Gönderilsin mi?", "Uyarı", JOptionPane.YES_NO_OPTION);
            
            if(dialogButton == 0){ // Evet
                
                try {
                     kullanici = sQLKullaniciIslemleri.kullaniciBul(girilenkullaniciAdi);
                    
                    if(kullanici == null){
                        
                        throw new NullPointerException();
                                
                    }else{
                        initComponents_2(true);
                        
                         mailAdresiBulunduMu = sQLKullaniciIslemleri.sifremiUnuttum(kullanici);
                     
                    //True veya false olma durumunu incelicez
                    
                    SwingWorker<Boolean,Integer> worker = new SwingWorker<Boolean, Integer>() {
                    @Override
                    protected Boolean doInBackground() throws Exception {
                        
                        for(int i = 120; i>=0; i--){
                            if(!sifreSonuc){
                              jLabel_Sayac.setText(String.valueOf(i));
                               Thread.sleep(1000);
                            }else{
                               sayacDurdur = true;
                               return true;
                            }
                            
                        }
                        
                        return true;
                        
                    }

                    @Override
                    protected void done() {
                       
                        initComponents_2(false);
                        if(!sayacDurdur){
                            JOptionPane.showMessageDialog(GirisEkrani.this, "Süreniz Bitti");
                        }else{
                            JOptionPane.showMessageDialog(GirisEkrani.this, "Kullanıcı Şifresi : " + kullanici.getKullaniciSifre());
                            jPasswordField_Sifre.setText(kullanici.getKullaniciSifre());
                        }
                    }
                    
                };
                worker.execute();
                    }
                    
                } catch (MessagingException ex) {
                    Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
                } catch(NullPointerException ex){
                    JOptionPane.showMessageDialog(this, "Girilen Kullanıcı Adı İle Kullanıcı Bulunamadı");
                } catch (SQLException ex) {
                    Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Kullanıcı adı girmediniz");
        }

    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseClicked

    private void jLabel_MoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jLabel_MoveMousePressed

    private void jLabel_MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseDragged
        this.setLocation(evt.getXOnScreen() - posX - 350, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_jLabel_MoveMouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
         posX = evt.getX();
         posY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
       this.setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jPanel_AnaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AnaPanelMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel_AnaPanelMousePressed

    private void jPanel_AnaPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AnaPanelMouseDragged
        this.setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_jPanel_AnaPanelMouseDragged

    private void jButton_GirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GirisYapActionPerformed
        
       this.sifreKurtarmaIslemi = jTextField_KurtarmaKodu.isVisible();  // Eğer Visible ise o zaman kullanıcımız Şifre kurtarma İşlemi yapıyor
        girisEkran = new GirisEkranIslemleri(jTextField_KullanıcıAdı, jTextField_KurtarmaKodu, jPasswordField_Sifre);
        
        String girilenKullaniciAdi = jTextField_KullanıcıAdı.getText();
        String girilenKullaniciSifre = new String(jPasswordField_Sifre.getPassword());
        
        boolean girisSonuc = false;
        boolean sifreSonuc = false;
        
        Kullanici kullanici;
        
        if(!sifreKurtarmaIslemi){ 
        
            try {
            // Giriş İşlemleri yapıyoruz
            
            girisSonuc = girisEkran.bosGirisKontrol();
            
            if(girisSonuc){
                
                 kullanici = sQLKullaniciIslemleri.kullaniciBul(girilenKullaniciAdi, girilenKullaniciSifre);
                 
                 if(kullanici == null){
                     throw  new NullPointerException();
                 }else{
                     this.setVisible(false);
                     KutuphaneSistemi kutuphaneSistemi = new KutuphaneSistemi(kullanici);
                     kutuphaneSistemi.setVisible(true);
                 }
            }   else{
                JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
            }
            } catch (SQLException ex) {
                Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
            } catch(NullPointerException ex){
                JOptionPane.showMessageDialog(this, "Hatalı Kullanıcı Adı veya Şifresi Girdiniz");

            }
            
        }else{ // Şifre Kurtarma İşemi yapıyorum
            sifreSonuc = girisEkran.sifreKurtar(mail.getSifreKurtarmaKodu());
            JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
        
            if(sifreSonuc){
                this.sifreSonuc = true;
            }else{
                JOptionPane.showMessageDialog(this, girisEkran.getSonucMesaj());
            }
        }
    }//GEN-LAST:event_jButton_GirisYapActionPerformed

    private void jTextField_KullanıcıAdıKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KullanıcıAdıKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
    }//GEN-LAST:event_jTextField_KullanıcıAdıKeyPressed

    private void jPasswordField_SifreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_SifreKeyPressed
         if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
    }//GEN-LAST:event_jPasswordField_SifreKeyPressed

    private void jTextField_KurtarmaKoduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KurtarmaKoduKeyPressed
         if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            jButton_GirisYap.doClick();
        }
    }//GEN-LAST:event_jTextField_KurtarmaKoduKeyPressed

    private void jLabel_HesapOlusturMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HesapOlusturMouseEntered
         jLabel_HesapOlustur.setForeground(Color.BLACK);
         jLabel_HesapOlustur.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel_HesapOlusturMouseEntered

    private void jLabel_HesapOlusturMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HesapOlusturMouseExited
         jLabel_HesapOlustur.setForeground(renkVeIconlar.getKirmizi());
    }//GEN-LAST:event_jLabel_HesapOlusturMouseExited

    private void jLabel_HesapOlusturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HesapOlusturMouseClicked
         this.setVisible(false);
         HesapOlustur hesapOlustur = new HesapOlustur();
         hesapOlustur.setVisible(true);
    }//GEN-LAST:event_jLabel_HesapOlusturMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        UIManager.setLookAndFeel(new FlatIntelliJLaf());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GirisYap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_HesabınızYoksa;
    private javax.swing.JLabel jLabel_HesapOlustur;
    private javax.swing.JLabel jLabel_KurtarmaMesajı;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Move;
    private javax.swing.JLabel jLabel_Sayac;
    private javax.swing.JLabel jLabel_SifremiUnuttum;
    private javax.swing.JLabel jLabel_UserLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_AnaPanel;
    private javax.swing.JPanel jPanel_GirisParametreleri;
    private javax.swing.JPanel jPanel_Girisİkon;
    private javax.swing.JPanel jPanel_Kullanıcıİkon;
    private javax.swing.JPanel jPanel_Navigasyon;
    private javax.swing.JPasswordField jPasswordField_Sifre;
    private javax.swing.JTextField jTextField_KullanıcıAdı;
    private javax.swing.JTextField jTextField_KurtarmaKodu;
    // End of variables declaration//GEN-END:variables
}
